[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"
  NODE_VERSION = "20"


[build]
  command = "yarn build:search"
  publish = "dist"
  ignore = "bash -c '[[ \"$BRANCH\" == cms/* ]] && echo \"Skipping CMS branch $BRANCH\" && exit 0 || exit 1'"

[[plugins]]
  package = "netlify-plugin-cypress"

[dev]
  framework = "hugo"
  targetPort = 3000

  [plugins.inputs]
    record = true